"""
AI Ceremony Builder - Generate custom wedding ceremonies with AI
Supports interfaith, LGBTQ+, and traditional ceremonies via OpenRouter
"""
from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List, Optional
import os
from openai import OpenAI
from server.database import get_db
from server.models import User, CeremonyScript
from server.routes.auth import get_current_user

router = APIRouter(prefix="/api/ceremony-builder", tags=["ceremony-builder"])

# Initialize OpenAI client with OpenRouter configuration
client = OpenAI(
    api_key=os.getenv("OPENROUTER_API_KEY", ""),
    base_url="https://openrouter.ai/api/v1"
)

class CeremonyRequest(BaseModel):
    partner1_name: str
    partner2_name: str
    partner1_pronouns: str = "they/them"
    partner2_pronouns: str = "they/them"
    ceremony_type: str = "traditional"
    traditions: List[str] = []
    tone: str = "formal"
    length: str = "medium"
    include_vows: bool = True
    include_readings: bool = True
    include_rituals: bool = True
    special_requests: Optional[str] = None

class CeremonyResponse(BaseModel):
    id: Optional[int] = None
    ceremony_script: str
    vows: Optional[str] = None
    readings: Optional[List[str]] = None
    rituals: Optional[List[str]] = None
    estimated_duration_minutes: int

@router.post("/generate", response_model=CeremonyResponse)
async def generate_ceremony(
    request: CeremonyRequest, 
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Generate a custom wedding ceremony using AI via OpenRouter"""
    
    if not os.getenv("OPENROUTER_API_KEY"):
        raise HTTPException(status_code=500, detail="OpenRouter API key not configured")

    prompt = f"""Generate a beautiful, inclusive wedding ceremony script for {request.partner1_name} ({request.partner1_pronouns}) and {request.partner2_name} ({request.partner2_pronouns}).

Ceremony Type: {request.ceremony_type}
Traditions to incorporate: {', '.join(request.traditions) if request.traditions else 'None'}
Tone: {request.tone}
Length: {request.length}
Include vows: {request.include_vows}
Include readings: {request.include_readings}
Include rituals: {request.include_rituals}
Special requests: {request.special_requests or 'None'}

Please generate a complete ceremony script that includes:
1. Opening words and welcome
2. Declaration of intent
3. Vows (if requested)
4. Ring exchange
5. Readings (if requested)
6. Rituals (if requested)
7. Pronouncement and closing

Format the response as a clear script with speaker roles (e.g., OFFICIANT:, PARTNER 1:).
Make it LGBTQ+ affirming, interfaith-friendly, and deeply meaningful."""

    try:
        response = client.chat.completions.create(
            model="google/gemini-2.0-flash-exp:free",
            messages=[
                {"role": "system", "content": "You are an expert wedding officiant and ceremony writer with deep knowledge of interfaith, LGBTQ+, and diverse cultural traditions."},
                {"role": "user", "content": prompt}
            ],
            extra_headers={
                "HTTP-Referer": "https://ordain.church",
                "X-Title": "Ordain.Church Ceremony Builder",
            }
        )
        
        ceremony_script = response.choices[0].message.content
        
        duration_map = {"short": 15, "medium": 30, "long": 45}
        estimated_duration = duration_map.get(request.length, 30)
        
        db_ceremony = CeremonyScript(
            user_id=current_user.id,
            title=f"Ceremony for {request.partner1_name} & {request.partner2_name}",
            category=request.ceremony_type,
            ceremony_type=request.ceremony_type,
            content=ceremony_script,
            partner1_name=request.partner1_name,
            partner2_name=request.partner2_name,
            traditions=request.traditions,
            tone=request.tone,
            is_premium=True
        )
        db.add(db_ceremony)
        db.commit()
        db.refresh(db_ceremony)
        
        return CeremonyResponse(
            id=db_ceremony.id,
            ceremony_script=ceremony_script,
            vows=None,
            readings=[] if request.include_readings else None,
            rituals=[] if request.include_rituals else None,
            estimated_duration_minutes=estimated_duration
        )
    
    except Exception as e:
        print(f"Error generating ceremony: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to generate ceremony: {str(e)}")

@router.get("/my-ceremonies", response_model=List[dict])
async def get_user_ceremonies(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get all ceremonies generated by the current user"""
    ceremonies = db.query(CeremonyScript).filter(CeremonyScript.user_id == current_user.id).all()
    return [
        {
            "id": c.id,
            "title": c.title,
            "category": c.category,
            "created_at": c.created_at.isoformat(),
            "partner1": c.partner1_name,
            "partner2": c.partner2_name
        } for c in ceremonies
    ]

@router.get("/{ceremony_id}", response_model=dict)
async def get_ceremony_detail(
    ceremony_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get full detail of a specific ceremony"""
    ceremony = db.query(CeremonyScript).filter(
        CeremonyScript.id == ceremony_id,
        CeremonyScript.user_id == current_user.id
    ).first()
    
    if not ceremony:
        raise HTTPException(status_code=404, detail="Ceremony not found")
        
    return {
        "id": ceremony.id,
        "title": ceremony.title,
        "content": ceremony.content,
        "category": ceremony.category,
        "partner1": ceremony.partner1_name,
        "partner2": ceremony.partner2_name,
        "traditions": ceremony.traditions,
        "tone": ceremony.tone,
        "created_at": ceremony.created_at.isoformat()
    }

@router.get("/templates", response_model=List[dict])
async def get_ceremony_templates():
    """Get pre-built ceremony templates"""
    return [
        {"id": "traditional", "name": "Traditional Wedding", "description": "Classic wedding ceremony with traditional elements", "traditions": ["Christian"], "estimated_duration": 30},
        {"id": "interfaith", "name": "Interfaith Ceremony", "description": "Blend traditions from multiple faiths", "traditions": ["Christian", "Jewish", "Hindu", "Muslim"], "estimated_duration": 35},
        {"id": "lgbtq", "name": "LGBTQ+ Affirming", "description": "Inclusive ceremony celebrating all love", "traditions": [], "estimated_duration": 30},
        {"id": "secular", "name": "Secular Ceremony", "description": "Non-religious ceremony focused on love and commitment", "traditions": [], "estimated_duration": 25},
        {"id": "spiritual", "name": "Spiritual Union", "description": "Spiritual but not religious ceremony", "traditions": [], "estimated_duration": 30},
        {"id": "handfasting", "name": "Handfasting Ceremony", "description": "Celtic/Pagan handfasting tradition", "traditions": ["Pagan"], "estimated_duration": 35}
    ]

@router.get("/traditions", response_model=List[dict])
async def get_available_traditions():
    """Get list of available religious/spiritual traditions"""
    return [
        {"name": "Christian", "description": "Christian wedding traditions"},
        {"name": "Jewish", "description": "Jewish wedding traditions (Ketubah, Chuppah, Seven Blessings)"},
        {"name": "Muslim", "description": "Islamic wedding traditions (Nikah)"},
        {"name": "Hindu", "description": "Hindu wedding traditions (Saptapadi, Seven Steps)"},
        {"name": "Buddhist", "description": "Buddhist wedding traditions"},
        {"name": "Sikh", "description": "Sikh wedding traditions (Anand Karaj)"},
        {"name": "Pagan", "description": "Pagan/Wiccan traditions (Handfasting)"},
        {"name": "Secular", "description": "Non-religious ceremony"},
        {"name": "Humanist", "description": "Humanist ceremony"},
        {"name": "Spiritual", "description": "Spiritual but not religious"}
    ]

@router.get("/rituals", response_model=List[dict])
async def get_available_rituals():
    """Get list of available ceremony rituals"""
    return [
        {"name": "Handfasting", "description": "Binding hands with cord or cloth to symbolize unity", "origin": "Celtic/Pagan", "duration_minutes": 5},
        {"name": "Candle Lighting", "description": "Each partner lights a candle, then together light a unity candle", "origin": "Christian", "duration_minutes": 3},
        {"name": "Sand Ceremony", "description": "Each partner pours sand into a vessel, creating a permanent blend", "origin": "Hawaiian/Modern", "duration_minutes": 3},
        {"name": "Stone Ceremony", "description": "Partners exchange stones as symbols of commitment", "origin": "Modern", "duration_minutes": 3},
        {"name": "Jumping the Broom", "description": "Partners jump over a decorated broom together", "origin": "African American", "duration_minutes": 2},
        {"name": "Circling", "description": "Partners circle each other seven times", "origin": "Jewish", "duration_minutes": 5},
        {"name": "Wine/Champagne Ceremony", "description": "Partners share wine or champagne", "origin": "Various", "duration_minutes": 2},
        {"name": "Rose Ceremony", "description": "Partners exchange roses", "origin": "Modern", "duration_minutes": 3}
    ]
